spring:
  application:
    name: magicdfs
  web:
    resources:
      static-locations: classpath:/static/,classpath:/resources/static/
mdfs:
  path: ${user.name}/mdfs
  isSync: true
  backupUrl: http://localhost:8081/upload
logging:
  level:
    root: info
    com.switchvov: debug
    javax: info
    sun: info
