server:
  port: 8090
mdfs:
  uploadPath: /Users/${user.name}/mdfs/${server.port}
  backupUrl: http://localhost:8091/upload
  downloadUrl: http://localhost:8090/download
  group: C${server.port}
  autoMd5: true
  syncBackup: true
  backupTopic: magic_dfs