spring:
  application:
    name: magicdfs
  profiles:
    active: 8090
logging:
  level:
    root: info
    com.switchvov: debug
    javax: info
    sun: info
rocketmq:
  name-server: localhost:9876
  producer:
    group: ${spring.application.name}-producer